### ISSUE TITLE
add "The Grand Unified Programming Theory: The Pure Function Pipeline Data Flow with Warehouse/Workshop Model"

### ISSUE THREAD

**Issue by linpengcheng** [AZHenley/hcse-dissertations#4]
[The Grand Unified Programming Theory: The Pure Function Pipeline Data Flow with Warehouse/Workshop Model ---- Lin Pengcheng](https://github.com/linpengcheng/PurefunctionPipelineDataflow)

**Comment by AZHenley** [comment]
Can you link me to a PDF of the dissertation? Where did you receive your PhD and who was your advisor?

**Comment by linpengcheng** [comment]
I am a Bachelor of Management, here is [my resume](https://github.com/linpengcheng/myresume)

My computer expertise is self-taught: Computer and its Applications, Junior College, Self-Study Examination, Fuzhou University.

This article needs to be improved and expanded before it can be officially published. It is currently referenced by [Dataflow programming in wikipedia](https://en.wikipedia.org/wiki/Dataflow_programming), [free-programming-books (Github's most popular repositories)](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md) , [Dataflow programming in wikimili](https://wikimili.com/en/Dataflow_programming) and saved in "github's Arctic Code Vault".

**Comment by AZHenley** [comment]
Sorry, this list is for dissertations.
